apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-mysql
  labels:
    app.kubernetes.io/app: webapp
    app.kubernetes.io/name: webapp-mysql
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: webapp
      app.kubernetes.io/name: webapp-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/app: webapp
        app.kubernetes.io/name: webapp-mysql
    spec:
      serviceAccountName: clo
      containers:
      - name: webapp-mysql
        image: 397002225899.dkr.ecr.us-east-1.amazonaws.com/clo835:final
        volumeMounts:
        - name: db-secret-volume
          mountPath: "/opt/app-secret-volumes"
          readOnly: true
        envFrom:
          - secretRef:
              name: db-secret
        env:
        - name: IMAGE_URL_PASS
          valueFrom: 
            configMapKeyRef:
              name: webapp-config
              key: IMAGE_URL_PASS
        - name: IMAGE_URL_FAIL
          valueFrom: 
            configMapKeyRef:
              name: webapp-config
              key: IMAGE_URL_FAIL
        - name: GROUP
          valueFrom: 
            configMapKeyRef:
              name: webapp-config
              key:  GROUP
        ports:
        - containerPort: 8080
      volumes:
        - name: db-secret-volume
          secret:
            secretName: db-secret